// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendor_Link_Point.Data;

#nullable disable

namespace Vendor_Link_Point.Migrations
{
    [DbContext(typeof(VendorLinkPointContext))]
    [Migration("20260531123234_CorrectionofKereskedoID")]
    partial class CorrectionofKereskedoID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vendor_Link_Point.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Elerheto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gyarto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KepUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KereskedoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Raktarkeszlet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Rendeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allapot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FizetesiMod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Vegosszeg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rendelesek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.RendelesTetel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Egysegar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("RendelesTetelek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Jatek", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.Product");

                    b.Property<int>("Korhatar")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Jatekok", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Ar = 12000m,
                            Elerheto = true,
                            Gyarto = "CD Projekt Red",
                            Kategoria = "Játékok",
                            KepUrl = "https://dummyimage.com/400x300/282c34/fff.png&text=Witcher+3",
                            KereskedoId = "VLP-7OF08QF3",
                            Leiras = "Az egyik legjobb nyílt világú szerepjáték Geralt kalandjaival.",
                            Nev = "The Witcher 3: Wild Hunt",
                            Raktarkeszlet = 5,
                            Korhatar = 18,
                            Tipus = "RPG"
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Konyv", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.Product");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.ToTable("Konyvek", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Ar = 5500m,
                            Elerheto = true,
                            Gyarto = "Európa Kiadó",
                            Kategoria = "Könyvek",
                            KepUrl = "https://dummyimage.com/400x300/282c34/fff.png&text=Konyv",
                            KereskedoId = "VLP-7OF08QF3",
                            Leiras = "Klasszikus fantasy regény, az epikus kaland kezdete.",
                            Nev = "A Gyűrűk Ura - A Gyűrű Szövetsége",
                            Raktarkeszlet = 30,
                            Isbn = "978-963-07-9204-5",
                            Szerzo = "J.R.R. Tolkien"
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.TV", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.Product");

                    b.Property<string>("Felbontas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Kepatlo")
                        .HasColumnType("int");

                    b.ToTable("TVk", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ar = 165000m,
                            Elerheto = true,
                            Gyarto = "Samsung",
                            Kategoria = "TV-k",
                            KepUrl = "https://dummyimage.com/400x300/282c34/fff.png&text=Samsung+TV",
                            KereskedoId = "VLP-7OF08QF3",
                            Leiras = "Kiváló minőségű okos TV 4K felbontással.",
                            Nev = "Samsung 55\" Smart 4K TV",
                            Raktarkeszlet = 12,
                            Felbontas = "4K UHD",
                            Kepatlo = 55
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Kereskedo", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.User");

                    b.Property<string>("Cegnev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KereskedoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Kereskedok", (string)null);
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Vasarlo", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.User");

                    b.Property<string>("SzallitasiCim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefonszam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Vasarlok", (string)null);
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Rendeles", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.User", "Vasarlo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vasarlo");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.RendelesTetel", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Rendeles", "Rendeles")
                        .WithMany("RendelesTetelek")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendor_Link_Point.Models.Product", "Termek")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rendeles");

                    b.Navigation("Termek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Jatek", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Jatek", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Konyv", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Konyv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.TV", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.TV", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Kereskedo", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Kereskedo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Vasarlo", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Vasarlo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Rendeles", b =>
                {
                    b.Navigation("RendelesTetelek");
                });
#pragma warning restore 612, 618
        }
    }
}
