// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendor_Link_Point.Data;

#nullable disable

namespace Vendor_Link_Point.Migrations
{
    [DbContext(typeof(VendorLinkPointContext))]
    [Migration("20260601091428_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vendor_Link_Point.Models.Ertekeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Pontszam")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Szoveg")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Ertekelesek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Elerheto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gyarto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KepUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("KereskedoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Leiras")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Raktarkeszlet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Rendeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allapot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FizetesiMod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SzallitasiCim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Vegosszeg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rendelesek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.RendelesTetel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Egysegar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("RendelesTetelek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Jatek", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.Product");

                    b.Property<int>("Korhatar")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Jatekok", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Ar = 8500m,
                            Elerheto = true,
                            Gyarto = "CD Projekt Red",
                            Kategoria = "Játékok",
                            KepUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmGIEPRaJ3z7E8MIG.png",
                            KereskedoId = "VLP-KOCKA",
                            Leiras = "Bújj Ríviai Geralt bőrébe ebben a hatalmas, nyílt világú kalandban.",
                            Nev = "The Witcher 3: Wild Hunt",
                            Raktarkeszlet = 30,
                            Korhatar = 18,
                            Tipus = "RPG"
                        },
                        new
                        {
                            Id = 5,
                            Ar = 24000m,
                            Elerheto = true,
                            Gyarto = "Warner Bros",
                            Kategoria = "Játékok",
                            KepUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202011/0919/cDKjqQc1QvM89tU33T94k8O6.png",
                            KereskedoId = "VLP-KOCKA",
                            Leiras = "Fedezd fel a varázslóvilágot a 19. században ebben a lenyűgöző játékban!",
                            Nev = "Hogwarts Legacy",
                            Raktarkeszlet = 15,
                            Korhatar = 16,
                            Tipus = "Akció-RPG"
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Konyv", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.Product");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.ToTable("Konyvek", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Ar = 5500m,
                            Elerheto = true,
                            Gyarto = "Európa Könyvkiadó",
                            Kategoria = "Könyvek",
                            KepUrl = "https://bookline.hu/zoom/bookline/092/10/92/27/0921092270.jpg",
                            KereskedoId = "VLP-KOCKA",
                            Leiras = "Minden idők leghíresebb fantasy regényének első része.",
                            Nev = "A Gyűrűk Ura - A Gyűrű Szövetsége",
                            Raktarkeszlet = 20,
                            Isbn = "9789630798150",
                            Szerzo = "J.R.R. Tolkien"
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.TV", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.Product");

                    b.Property<string>("Felbontas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Kepatlo")
                        .HasColumnType("int");

                    b.ToTable("TVk", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ar = 165000m,
                            Elerheto = true,
                            Gyarto = "Samsung",
                            Kategoria = "TV-k",
                            KepUrl = "https://images.samsung.com/is/image/samsung/p6pim/hu/ue55cu7172uxxh/gallery/hu-crystal-uhd-cu7000-ue55cu7172uxxh-536306536?$650_519_PNG$",
                            KereskedoId = "VLP-ELEKTRO",
                            Leiras = "Lélegzetelállító 4K felbontás és kristálytiszta színek okos funkciókkal.",
                            Nev = "Samsung 55\" 4K Smart UHD TV",
                            Raktarkeszlet = 12,
                            Felbontas = "4K UHD",
                            Kepatlo = 55
                        },
                        new
                        {
                            Id = 2,
                            Ar = 540000m,
                            Elerheto = true,
                            Gyarto = "LG",
                            Kategoria = "TV-k",
                            KepUrl = "https://www.lg.com/hu/images/televiziok/md07593256/gallery/D-01.jpg",
                            KereskedoId = "VLP-ELEKTRO",
                            Leiras = "Tökéletes fekete és végtelen kontraszt az LG OLED technológiájával.",
                            Nev = "LG OLED 65\" C3",
                            Raktarkeszlet = 5,
                            Felbontas = "4K OLED",
                            Kepatlo = 65
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Kereskedo", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.User");

                    b.Property<string>("Cegnev")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KereskedoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.ToTable("Kereskedok", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "elektro@vendor.hu",
                            Jelszo = "7jqVtG5ypHGQXHK6YYkJWA==:Juoi47jOMwjH7dtqmA2zN6rRQXGZuoSJkewbDQoCcP8=",
                            Nev = "Kovács Elek",
                            Role = "Kereskedo",
                            Cegnev = "Elektro Kft.",
                            KereskedoId = "VLP-ELEKTRO"
                        },
                        new
                        {
                            Id = 2,
                            Email = "kocka@vendor.hu",
                            Jelszo = "7jqVtG5ypHGQXHK6YYkJWA==:Juoi47jOMwjH7dtqmA2zN6rRQXGZuoSJkewbDQoCcP8=",
                            Nev = "Nagy Károly",
                            Role = "Kereskedo",
                            Cegnev = "Kocka Barlang",
                            KereskedoId = "VLP-KOCKA"
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Vasarlo", b =>
                {
                    b.HasBaseType("Vendor_Link_Point.Models.User");

                    b.Property<string>("SzallitasiCim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefonszam")
                        .HasColumnType("longtext");

                    b.ToTable("Vasarlok", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "vevo@vendor.hu",
                            Jelszo = "7jqVtG5ypHGQXHK6YYkJWA==:Juoi47jOMwjH7dtqmA2zN6rRQXGZuoSJkewbDQoCcP8=",
                            Nev = "Teszt Vásárló",
                            Role = "Vasarlo",
                            SzallitasiCim = "1055 Budapest, Kossuth Lajos tér 1-3.",
                            Telefonszam = "+36301234567"
                        });
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Ertekeles", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", "Termek")
                        .WithMany("Ertekelesek")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendor_Link_Point.Models.User", "Vasarlo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Termek");

                    b.Navigation("Vasarlo");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Rendeles", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.User", "Vasarlo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vasarlo");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.RendelesTetel", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Rendeles", "Rendeles")
                        .WithMany("RendelesTetelek")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vendor_Link_Point.Models.Product", "Termek")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rendeles");

                    b.Navigation("Termek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Jatek", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Jatek", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Konyv", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Konyv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.TV", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.TV", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Kereskedo", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Kereskedo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Vasarlo", b =>
                {
                    b.HasOne("Vendor_Link_Point.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Vendor_Link_Point.Models.Vasarlo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Product", b =>
                {
                    b.Navigation("Ertekelesek");
                });

            modelBuilder.Entity("Vendor_Link_Point.Models.Rendeles", b =>
                {
                    b.Navigation("RendelesTetelek");
                });
#pragma warning restore 612, 618
        }
    }
}
